In [6]:
import sys
print(sys.executable)
import warnings
warnings.filterwarnings("ignore")

/usr/local/bin/python3

In [7]:
%pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.4.4)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/afsarazam/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/afsarazam/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import numpy as np 
import os

# Option 1: Use the correct relative path
# If the file is in your current working directory:
df = pd.read_csv("/Users/afsarazam/Desktop/ML tools& tech/waste_data.csv")

# Option 2: Use an absolute path
# Replace with your actual file path:
# df = pd.read_csv("/full/path/to/waste_data.csv")

# Option 3: Print current working directory to help locate the file
print("Current working directory:", os.getcwd())

# Option 4: If spaces in the path are causing issues, escape them properly
# df = pd.read_csv("Desktop/ML tools & tech/waste_data.csv")  # Note the space after 'tools'

Current working directory: /Users/afsarazam/Desktop/ML tools& tech

In [9]:
df.head()

,Day,Temperature,MC(%),pH,C/N Ratio,Ammonia(mg/kg),Nitrate(mg/kg),TN(%),TOC(%),EC(ms/cm),OM(%),T Value,GI(%),Score
0,0,35.463,60.0000,5.7345,26.7755,2515.0,325.49,1.80632,48.365121,1.7846,83.381469,1.000000,32.8821,28.042095
1,3,41.866,56.8814,7.1327,23.0494,3449.1,302.42,1.92498,44.369634,2.4366,76.493249,0.860839,39.4615,36.185328
2,6,59.134,53.0847,7.9646,20.4697,5197.6,243.40,1.83675,37.597721,3.0118,64.818472,0.764494,30.5469,37.074037
3,9,53.119,49.4237,8.1770,18.7500,1940.1,203.99,1.78550,33.478125,3.1566,57.716287,0.700267,63.1219,51.246933
4,12,38.955,45.2203,8.0177,17.0303,814.4,200.52,1.91893,32.679954,3.5596,56.340240,0.636040,79.4691,59.698282

In [10]:
df.isnull().sum()

Day               0
Temperature       0
MC(%)             0
pH                0
C/N Ratio         0
Ammonia(mg/kg)    0
Nitrate(mg/kg)    0
TN(%)             0
TOC(%)            0
EC(ms/cm)         0
OM(%)             0
T Value           0
GI(%)             0
Score             0
dtype: int64

In [11]:
df = df.drop(columns=[
    "Day",
    "T Value",
    "Score"
])

print(df.head())

   Temperature    MC(%)      pH  C/N Ratio  Ammonia(mg/kg)  Nitrate(mg/kg)  \
0       35.463  60.0000  5.7345    26.7755          2515.0          325.49
1       41.866  56.8814  7.1327    23.0494          3449.1          302.42
2       59.134  53.0847  7.9646    20.4697          5197.6          243.40
3       53.119  49.4237  8.1770    18.7500          1940.1          203.99
4       38.955  45.2203  8.0177    17.0303           814.4          200.52

     TN(%)     TOC(%)  EC(ms/cm)      OM(%)    GI(%)
0  1.80632  48.365121     1.7846  83.381469  32.8821
1  1.92498  44.369634     2.4366  76.493249  39.4615
2  1.83675  37.597721     3.0118  64.818472  30.5469
3  1.78550  33.478125     3.1566  57.716287  63.1219
4  1.91893  32.679954     3.5596  56.340240  79.4691

In [12]:
def assign_waste_type(cn):
    if cn < 20:
        return "Vegetable"
    elif cn <= 30:
        return "Mixed"
    else:
        return "Dry Leaves"

df["Waste_Type"] = df["C/N Ratio"].apply(assign_waste_type)

print(df[["C/N Ratio", "Waste_Type"]])

     C/N Ratio Waste_Type
0    26.775500      Mixed
1    23.049400      Mixed
2    20.469700      Mixed
3    18.750000  Vegetable
4    17.030300  Vegetable
..         ...        ...
447  26.215385      Mixed
448  17.751969  Vegetable
449  14.924242  Vegetable
450  13.865455  Vegetable
451  13.269231  Vegetable

[452 rows x 2 columns]

In [13]:
def assign_aeration(mc):
    if mc < 40:
        return "High"
    elif mc <= 60:
        return "Medium"
    else:
        return "Low"

df["Aeration"] = df["MC(%)"].apply(assign_aeration)

print(df[["MC(%)","Aeration"]])

       MC(%) Aeration
0    60.0000   Medium
1    56.8814   Medium
2    53.0847   Medium
3    49.4237   Medium
4    45.2203   Medium
..       ...      ...
447  56.8008   Medium
448  45.5358   Medium
449  40.3880   Medium
450  40.3495   Medium
451  40.4336   Medium

[452 rows x 2 columns]

In [14]:
def assign_smell_level(ammonia):
    if ammonia < 50:
        return "Low"
    elif ammonia <= 150:
        return "Medium"
    else:
        return "High"

df["Smell_Level"] = df["Ammonia(mg/kg)"].apply(assign_smell_level)

print(df[["Ammonia(mg/kg)","Smell_Level"]])

     Ammonia(mg/kg) Smell_Level
0       2515.000000        High
1       3449.100000        High
2       5197.600000        High
3       1940.100000        High
4        814.400000        High
..              ...         ...
447      522.903653        High
448      179.822071        High
449      146.696953      Medium
450      108.839674      Medium
451       98.000000      Medium

[452 rows x 2 columns]

In [15]:
df.head()

,Temperature,MC(%),pH,C/N Ratio,Ammonia(mg/kg),Nitrate(mg/kg),TN(%),TOC(%),EC(ms/cm),OM(%),GI(%),Waste_Type,Aeration,Smell_Level
0,35.463,60.0000,5.7345,26.7755,2515.0,325.49,1.80632,48.365121,1.7846,83.381469,32.8821,Mixed,Medium,High
1,41.866,56.8814,7.1327,23.0494,3449.1,302.42,1.92498,44.369634,2.4366,76.493249,39.4615,Mixed,Medium,High
2,59.134,53.0847,7.9646,20.4697,5197.6,243.40,1.83675,37.597721,3.0118,64.818472,30.5469,Mixed,Medium,High
3,53.119,49.4237,8.1770,18.7500,1940.1,203.99,1.78550,33.478125,3.1566,57.716287,63.1219,Vegetable,Medium,High
4,38.955,45.2203,8.0177,17.0303,814.4,200.52,1.91893,32.679954,3.5596,56.340240,79.4691,Vegetable,Medium,High

In [16]:
from sklearn.preprocessing import LabelEncoder

le_waste = LabelEncoder()
le_aeration = LabelEncoder()
le_smell = LabelEncoder()

df["Waste_Type"] = le_waste.fit_transform(df["Waste_Type"])
df["Aeration"] = le_aeration.fit_transform(df["Aeration"])
df["Smell_Level"] = le_smell.fit_transform(df["Smell_Level"])
print(df.head())

   Temperature    MC(%)      pH  C/N Ratio  Ammonia(mg/kg)  Nitrate(mg/kg)  \
0       35.463  60.0000  5.7345    26.7755          2515.0          325.49
1       41.866  56.8814  7.1327    23.0494          3449.1          302.42
2       59.134  53.0847  7.9646    20.4697          5197.6          243.40
3       53.119  49.4237  8.1770    18.7500          1940.1          203.99
4       38.955  45.2203  8.0177    17.0303           814.4          200.52

     TN(%)     TOC(%)  EC(ms/cm)      OM(%)    GI(%)  Waste_Type  Aeration  \
0  1.80632  48.365121     1.7846  83.381469  32.8821           1         2
1  1.92498  44.369634     2.4366  76.493249  39.4615           1         2
2  1.83675  37.597721     3.0118  64.818472  30.5469           1         2
3  1.78550  33.478125     3.1566  57.716287  63.1219           2         2
4  1.91893  32.679954     3.5596  56.340240  79.4691           2         2

   Smell_Level
0            0
1            0
2            0
3            0
4            0

In [17]:
def compost_status(gi):
    if gi >= 80:
        return "Ready"
    else:
        return "Not Ready"

df["Compost_Status"] = df["GI(%)"].apply(compost_status)

In [18]:
df = df.drop(columns=["GI(%)"])

In [19]:
df

,Temperature,MC(%),pH,C/N Ratio,Ammonia(mg/kg),Nitrate(mg/kg),TN(%),TOC(%),EC(ms/cm),OM(%),Waste_Type,Aeration,Smell_Level,Compost_Status
0,35.463,60.0000,5.7345,26.775500,2515.000000,325.49,1.80632,48.365121,1.784600,83.381469,1,2,0,Not Ready
1,41.866,56.8814,7.1327,23.049400,3449.100000,302.42,1.92498,44.369634,2.436600,76.493249,1,2,0,Not Ready
2,59.134,53.0847,7.9646,20.469700,5197.600000,243.40,1.83675,37.597721,3.011800,64.818472,1,2,0,Not Ready
3,53.119,49.4237,8.1770,18.750000,1940.100000,203.99,1.78550,33.478125,3.156600,57.716287,2,2,0,Not Ready
4,38.955,45.2203,8.0177,17.030300,814.400000,200.52,1.91893,32.679954,3.559600,56.340240,2,2,0,Not Ready
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,40.800,56.8008,7.3200,26.215385,522.903653,0.00,1.95000,51.120000,1.514333,86.820513,1,2,0,Not Ready
448,17.600,45.5358,7.2300,17.751969,179.822071,0.00,2.54000,45.090000,1.387000,84.907598,2,2,0,Ready
449,20.200,40.3880,7.4200,14.924242,146.696953,0.00,2.64000,39.400000,1.519000,83.511977,2,2,2,Ready
450,20.700,40.3495,7.5300,13.865455,108.839674,0.00,2.75000,38.130000,1.631667,81.732816,2,2,2,Ready
451,24.100,40.4336,7.8300,13.269231,98.000000,0.00,2.86000,37.950000,1.727100,78.106180,2,2,2,Ready

# Compost Modal

In [20]:

X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

print("X columns:", X.columns)
print("y name:", y.name)

X columns: Index(['Temperature', 'MC(%)', 'pH', 'C/N Ratio', 'Ammonia(mg/kg)',
       'Nitrate(mg/kg)', 'TN(%)', 'TOC(%)', 'EC(ms/cm)', 'OM(%)', 'Waste_Type',
       'Aeration', 'Smell_Level'],
      dtype='str')
y name: Compost_Status

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [22]:
X_train = X_train.values
X_test = X_test.values

In [23]:
model = RandomForestClassifier(n_estimators=50, random_state=1)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=1)

In [24]:
y_pred = model.predict(X_test)
print("acc:", accuracy_score(y_test, y_pred))

acc: 0.9120879120879121

In [25]:
X_test

array([[16.508  , 39.8272 ,  8.0887 , ...,  2.     ,  0.     ,  0.     ],
       [41.241  , 45.426  ,  6.4277 , ...,  1.     ,  2.     ,  0.     ],
       [34.024  , 35.301  ,  7.7452 , ...,  2.     ,  0.     ,  0.     ],
       ...,
       [18.809  , 74.337  ,  8.5018 , ...,  2.     ,  1.     ,  0.     ],
       [50.124  , 56.125  ,  6.25177, ...,  1.     ,  2.     ,  0.     ],
       [44.237  , 51.864  ,  8.0957 , ...,  1.     ,  2.     ,  0.     ]],
      shape=(91, 13))

In [26]:
y_test = model.predict(X_test)

In [27]:
X_train

array([[21.246  , 49.584  ,  6.51301, ...,  0.     ,  2.     ,  0.     ],
       [63.6    , 21.72   ,  6.25   , ...,  2.     ,  0.     ,  0.     ],
       [21.591  , 41.01   ,  8.6204 , ...,  2.     ,  2.     ,  0.     ],
       ...,
       [16.4    , 54.5298 ,  6.61   , ...,  2.     ,  2.     ,  0.     ],
       [31.617  , 42.5078 ,  8.3051 , ...,  2.     ,  2.     ,  0.     ],
       [23.214  , 79.036  ,  8.1784 , ...,  2.     ,  1.     ,  0.     ]],
      shape=(361, 13))

In [28]:
print(X_train.dtype)
print(X_test.dtype)

float64
float64

In [29]:
data = [[
    26,     # Temperature
    45,     # MC%
    7.2,    # pH 
    28,     # C/N
    5,      # Ammonia
    65,     # Nitrate
    2.2,    # TN
    30,     # TOC
    1.0,    # EC
    50,     # OM
    1,      # Waste_Type
    2,      # Aeration
    0       # Smell_Level
]]
pred = model.predict(data)
print("Compost Status:", pred)

Compost Status: ['Not Ready']

In [30]:
df.head()

,Temperature,MC(%),pH,C/N Ratio,Ammonia(mg/kg),Nitrate(mg/kg),TN(%),TOC(%),EC(ms/cm),OM(%),Waste_Type,Aeration,Smell_Level,Compost_Status
0,35.463,60.0000,5.7345,26.7755,2515.0,325.49,1.80632,48.365121,1.7846,83.381469,1,2,0,Not Ready
1,41.866,56.8814,7.1327,23.0494,3449.1,302.42,1.92498,44.369634,2.4366,76.493249,1,2,0,Not Ready
2,59.134,53.0847,7.9646,20.4697,5197.6,243.40,1.83675,37.597721,3.0118,64.818472,1,2,0,Not Ready
3,53.119,49.4237,8.1770,18.7500,1940.1,203.99,1.78550,33.478125,3.1566,57.716287,2,2,0,Not Ready
4,38.955,45.2203,8.0177,17.0303,814.4,200.52,1.91893,32.679954,3.5596,56.340240,2,2,0,Not Ready

# Smell Modal

In [31]:
X = df.drop(columns=["Smell_Level", "Compost_Status", "Ammonia(mg/kg)"])
y = df["Smell_Level"]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [33]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [34]:
y_pred = model.predict(X_test)

print("acc:", accuracy_score(y_test, y_pred))

acc: 0.978021978021978

In [35]:
print("X columns:", X.columns)
print("y name:", y.name)

X columns: Index(['Temperature', 'MC(%)', 'pH', 'C/N Ratio', 'Nitrate(mg/kg)', 'TN(%)',
       'TOC(%)', 'EC(ms/cm)', 'OM(%)', 'Waste_Type', 'Aeration'],
      dtype='str')
y name: Smell_Level

In [36]:
data = [[
    25,     # Temperature
    45,     # MC% (optimal)
    7.0,    # pH (neutral)
    30,     # C/N (balanced)
    60,     # Nitrate (high = stable compost)
    2.0,    # TN
    30,     # TOC
    1.0,    # EC
    50,     # OM
    1,      # Waste_Type (Mixed)
    2       # Aeration (High)
]]
pred = model.predict(data)

print("Smell Level:", pred)

Smell Level: [0]